### ISSUE TITLE
Metadata propagation doesn't do anything

### ISSUE THREAD

**Issue by mmuzikar** [hawtio/hawtio-operator#110]
When creating a Hawtio instance and setting the `metadataPropagation` to add labels and annotations to the created resources doesn't do anything, there's no error in the operator log and the resources are created as if no `metadataPropagation` was set at all.

Example CR spec:
```
spec:
  auth: {}
  config:
    about: {}
    branding: {}
    online:
      consoleLink: {}
  metadataPropagation:
    annotations:
      - key=value
    labels:
      - asdf=aaaa
  nginx: {}
  rbac: {}
  resources: {}
  route:
    caCert:
      key: ''
    certSecret: {}
  type: Namespace
```

**Comment by mmuzikar** [comment]
ahh maybe I don't understand the setting correctly - is it like a filter for which labels and annotations from the Hawtio CR to propagate?

**Comment by phantomjinx** [comment]
Looking at the code, I believe you can add Annotations and Labels to the Hawtio CR. By default, all of these will be propogated to the operand resources. The `metadataPropagation` filters the propogation by pattern matching. Not sure why this function is part of the operator as does not appear massively useful to me but maybe  users require it??

**Comment by tadayosi** [comment]
yes it's requested by a user. if you dig into the code history you'll find the ticket number.

**Comment by phantomjinx** [comment]
@mmuzikar 

This is working correctly and functions by propogating labels / annotations that are added to the CR via the propogation filtering.

```
apiVersion: v1
items:
- apiVersion: hawt.io/v1
  kind: Hawtio
  metadata:
    annotations:
      awesome.com/env: dev
      awesome.com/param1: value1
      awesome.com/param2: value2
      noprop.com/noprop: nothing
    labels:
      env: dev
      param1: value1
      param2: value2
    name: hawtio-online
  spec:
    auth:
      clientCertCheckSchedule: '* */12 * * *'
      clientCertExpirationPeriod: 24
    config:
      metadataPropagation:
        annotations:
        - awesome.com/*
        labels:
        - env
        - param*
...
```

So the annotations and labels added to the `metadata` section of the CR above are propogated to the resources of the hawtio-online operand, with the exception of `noprop.com/noprop` which is not included in the `metadataPropogation` property.
