### ISSUE TITLE
Restrict Secret read ClusterRole to the openshift-service-ca namespace

### ISSUE THREAD

**Issue by astefanutti** [hawtio/hawtio-operator#37]
Following #34, the ClusterRole permission required to read the service signing certificate secret should be restricted to the `openshift-service-ca` namespace.

The minimal RBAC can be achieved with:

ca_role.yaml:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hawtio-operator-ca
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - signing-key
  verbs:
  - get
```

ca_role_binding.yaml:

```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hawtio-operator
  namespace: openshift-service-ca
subjects:
- kind: ServiceAccount
  name: hawtio-operator
  namespace: hawtio
roleRef:
  kind: ClusterRole
  name: hawtio-operator-ca
  apiGroup: rbac.authorization.k8s.io
```

That gives:

```console
$ kubectl auth can-i get secrets/signing-key -n openshift-service-ca --as system:serviceaccount:hawtio:hawtio-operator
yes
```

The problem is to make is work with `kustomize`. We have to find a way to avoid it changes the `openshift-service-ca` namespace.

It seems it is possible to work-around `kustomize` [aggresive namespace replacement](https://github.com/kubernetes-sigs/kustomize/issues/880), by using patches, e.g.:

deploy/kustomization.yaml:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster_role_binding.yaml
- cluster_role.yaml
- ca_role.yaml
- ca_role_binding.yaml
- role.yaml
- role_binding.yaml
- service_account.yaml
- operator.yaml

patches:
- path: patch.json
  target:
    kind: Deployment
- path: patch.json
  target:
    kind: Role
- path: patch.json
  target:
    kind: ServiceAccount
- path: patch.json
  target:
    kind: RoleBinding
    namespace: ^$
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: TEST
  target:
    kind: RoleBinding
    namespace: openshift-service-ca
```

deploy/patch.json:

```json
[
  {"op": "replace", "path": "/metadata/namespace", "value": "TEST"}
]
```

The new problem is that OLM bundle generation with `operator-sdk generate bundle` does not seem to managed to take the RoleBinding into account. Actual, that seems impossible to describe such a RoleBinding (from a ClusterRole to a namespace) in the CSV resource. The way to do it seems to include the RoleBinding into the OLM bundle directory, but that has to be tested.
