### ISSUE TITLE
Add a conversion hook to ensure CRD apis can be converted from v1alphav1 to v1

### ISSUE THREAD

**Issue by phantomjinx** [hawtio/hawtio-operator#88]
Since one version of a CRD api can be stored in the etcd, other versions are converted into this version. Without a conversion hook, the only migration that takes place is the api version number. In order to facilitate the conversion of properties then a conversion hook should be added and broadcast to the cluster.

Reference: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#before-you-begin

**Comment by phantomjinx** [comment]
Looking into this, the evidence indicates that a conversion webhook is unnecessary for the dropping of the `version` property.
Experiment:

1. Deploy the v1 CRD:
```
cd deploy
kustomize --load-restrictor LoadRestrictionsNone build setup | kubectl apply -f -
```

2. Create a v1alpha1 version file of the CR as `hawtio_v1alpha1_hawtio_cr.yaml`, eg.
```
apiVersion: hawt.io/v1alpha1
kind: Hawtio
metadata:
  name: hawtio-online-v1alpha1
spec:
  type: Namespace
  replicas: 1
  version: 1.0.0
  auth:
    clientCertCheckSchedule: "* */12 * * *"
    clientCertExpirationPeriod: 24

  resources:
    limits:
      cpu: "1"
      memory: 200Mi
    requests:
      cpu: 200m
      memory: 32Mi
```

3. Deploy the `v1alpha1` CR
```
oc apply -f hawtio_v1alpha1_hawtio_cr.yaml
```

4. Get the contents of the CR from the cluster
```
oc get Hawtio -o yaml
```

The resulting data will indicate show:
a. the `hawtio` api version has been converted to v1
b. the `version` property has been dropped from the `spec`

Therefore, this indicates that a new `v1alpha1` CR will be automatically converted upon application to the cluster.

The remaining question is whether an existing Hawtio CR that is already installed on a cluster under the v1alpha1 CRD, upgraded in the same manner when the new v1 CRD is installed. At this point, looking at the history of other projects, the initial answer to this question is that this is the case.
